### ISSUE TITLE
FluxComponent is not recognized as React component

### ISSUE THREAD

**Issue by jimzhan** [acdlite/flummox#202] opened 2015-05-28 01:53 UTC
```javascript
const routes = (
  <Route name="app" handler={Main} path="/">
    <DefaultRoute name="home" handler={Home} />
    <Route name="about" path="/about" handler={About} />
  </Route>
);

const router = Router.create({
  routes: routes,
  location: Router.HistoryLocation
});


router.run((Handler, state) => {
  React.render(
    <FluxComponent flux={flux}>
      <Handler {...state} />
    </FluxComponent>,
    document.body
  );
});
```

```javascript
warning.js:48 Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
2015-05-28 09:40:52.870 warning.js:48 Warning: Only functions or strings can be mounted as React components.
2015-05-28 09:40:52.871 ReactDefaultInjection.js:53 Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
```

React: 0.13.3
Flummox: 3.5.2

Meanwhile, may I suggest that we keep the docs in sync in detail, or better yet, remove the duplicated/misleading variable/definitions, e.g. 

```javascript
import {Flux} from 'flummox';
// is exactly same thing as
import {Flummox} from 'flummox';
```

```javascript
const actions = flux.getActions('SomeDomain');
this.register(actions.doSomething, this.onDoSomething);

// is exactly same as

const actionIds = flux.getActionIds('SomeDomain');
this.register(actionIds.doSomething, this.onDoSomething);
```

**Comment by bdowning** [comment] 2015-05-28 05:06
Are you just missing

```javascript
import FluxComponent from 'flummox/component';
```

perhaps?

**Comment by jimzhan** [comment] 2015-05-28 06:53
@bdowning I'm using eslint on Vim, so, nope.

**Comment by johanneslumpe** [comment] 2015-05-31 07:42
@jimzhan I cannot reproduce your error. I tried your example without the wrapping react-router callback and it worked fine. Can you please post more complete code, showing how you import the component?

**Comment by johanneslumpe** [comment] 2015-06-01 17:48
Ok, closing this for now. If you still have this issue, please report back here and we can re-open this :)

**Closed by johanneslumpe** 2015-06-01 17:48 UTC

**Comment by parisholley** [comment] 2015-09-29 16:04
hitting this as well

**Comment by parisholley** [comment] 2015-09-29 16:11
to work around, I had to place the fluxcomponent on the first handler. in your example, this was "{Main}". Trying to wrap the <Route> tags seem to be problematic
