### ISSUE TITLE
Rejected promise from flummox action is causing uncaught error in console despite that it was catched

### ISSUE THREAD

**Issue by msimulcik** [acdlite/flummox#100] opened 2015-03-17 13:38 UTC
Hi, I'm using flummox 2.13.1 and have problem with handling rejected promises returned from flummox actions. Here is my code:

```javascript
'use strict';

import 'babel/polyfill';
import { Actions, Flummox } from 'flummox';

class MyActions extends Actions {
  async alwaysReject() {
      return await Promise.reject({foo: 1});
  }
}

class Flux extends Flummox {
  constructor() {
    super();

    this.createActions('my', MyActions);
  }
}

let flux = new Flux();

//test with flummox action
flux.getActions('my').alwaysReject().catch(err => {console.log('catched rejection from flummox action:', err)});


//test with regular function
async function alwaysReject() {
  return await Promise.reject({bar: 1});
}

alwaysReject().catch(err => {console.log('catched rejection from regular function:', err)});
```

It properly executes code from catch handler and logs to console, but also prints Uncaught error message to console. It is not happening when rejected promise is returned from regular async function. Here is screenshot from Chrome developer tools:

![flummox](https://cloud.githubusercontent.com/assets/6518872/6688229/12ad632c-ccb2-11e4-87bc-58753bc3fae1.PNG)

Am I doing something wrong or it is expected behavior?

**Comment by acdlite** [comment] 2015-03-17 13:49
This is a duplicate of #62. You can read the discussion there for an explanation of why it works this way. But no, you're not doing anything wrong.

**Comment by msimulcik** [comment] 2015-03-17 14:12
Yes, I read it before I created this issue, but I don't think it explains this. I understand that caller of the action is responsible for handling potentially rejected promises and that is exactly what I'm trying to do in the code above. I catch the rejected promise, but still has Uncaught error in the console. What I expect, is same behavior as with regular function (if rejection is caught, there is no error message in console).

**Comment by acdlite** [comment] 2015-03-17 14:17
Oh I see what you mean. Hmmm, that's interesting. Not sure where the uncaught promise would be in this case... though I'm not 100% sure how the devtools determine if a promise is caught or not.

**Comment by msimulcik** [comment] 2015-03-17 14:37
The strange thing is that I can't get the same behavior without using flummox actions. Everything is working as expected (no error in the console) so I don't think there is something wrong with the devtools. I will try to find out what it causing it in flummox.

**Comment by acdlite** [comment] 2015-03-17 15:51
@msimulcik I believe I figured it out. I'll fix as soon as I get the chance.

**Comment by msimulcik** [comment] 2015-03-17 15:56
Great, thank you.

**Comment by acdlite** [comment] 2015-03-17 17:25
Okay I just released v2.13.2 (and v3.1.1) which I believe fixes this. Please let me know.

**Comment by msimulcik** [comment] 2015-03-17 20:27
It is OK in 2.13.2. Thanks for quick fix.

**Comment by acdlite** [comment] 2015-03-17 20:28
Awesome, thank you!

**Closed by acdlite** 2015-03-17 20:28 UTC

**Comment by julen** [comment] 2015-03-17 22:01
FTR: I was also hitting this and the fix did the trick. Thanks for taking action so quickly!
