### ISSUE TITLE
Issue with context when using FluxComponent throughout the tree

### ISSUE THREAD

**Issue by bradleyboy** [acdlite/flummox#85] opened 2015-03-13 08:07 UTC
Hello - Thanks for flummox, really enjoying it so far :+1: 

I've either stumbled upon an issue or am misunderstanding something. Based on what I've read in the docs and in [this example](https://github.com/acdlite/flummox/issues/70#issuecomment-78063783), I was under the impression that you can define flux at or near the top of your tree, then all FluxComponent instances below that will be able to access the flux instance via context. That doesn't seem to be working for me, I get this error:

> Error: fluxMixin: Could not find Flux instance. Ensure that your component has either `this.context.flux` or `this.props.flux`.

To be sure it wasn't something specific to my app, I forked flummox and added a test to show you what I mean. This is currently failing in my branch:

https://github.com/bradleyboy/flummox/blob/master/src/addons/__tests__/FluxComponent-test.js#L179-L213

**Comment by acdlite** [comment] 2015-03-13 12:53
Hi! First of all, thank you thank you thank you for sending me a test case :+1: It makes things so much easier.

I think this may have something to do with `React.cloneElement()` not passing context. For now, I was able to fix you test case by changing your TopView to use the custom `render` prop:

```js
class TopView extends React.Component {
  render() {
    return (
      <FluxComponent
        flux={flux}
        render={() => <SubView />}
      />
    );
  }
}
```

Thank you for bringing this to my attention. I will investigate and either (ideally) fix it or document the solution posted here.

**Comment by acdlite** [comment] 2015-03-13 13:01
To clarify, the issue is with adding Flux to context, not retrieving it once it's there. In addition to the one above, another solution is to manually add the Flux instance to context using `getChildContext()`, but that's not ideal, either.

**Comment by netgusto** [comment] 2015-03-20 20:16
Not sure if this is related, but I have similar problems when using a `<FluxComponent>` down the tree, under a react-router's `<RouteHandler>`.

It seems that stores and flux prop'd on the top `<FluxComponent>` are not propagated down the tree.

As a workaround, on the child: 

```jsx
<div>
    <UIPageHeader icon="star" text='Administration' />
    <FluxComponent {...this.props}>
        <DemoList />
    </FluxComponent>
</div>
```

The important part is : `{...this.props}`

**Comment by acdlite** [comment] 2015-03-23 20:15
@netgusto I think your issue stems from the fact that FluxComponent only adds props to its immediate children. If you post a fuller snippet in a separate issue I will take a look.

Closing so we can follow this issue here: https://github.com/acdlite/flummox/issues/111#issuecomment-85172486 Read my comment there for an explanation of the context regression.

**Closed by acdlite** 2015-03-23 20:15 UTC
