### ISSUE TITLE
Warning on the website 

### ISSUE THREAD

**Issue by dozoisch** [acdlite/flummox#164] opened 2015-04-25 01:46 UTC
Navigating to  http://acdlite.github.io/flummox/docs/guides/quick-start gave me the following warning:

>Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) `lass="language-js">` 
`<span class="token k`
 (server) `lass="language-js">`
`import { Actions } f`

Weird warning about server side rendering being different than the client side rendering.

**Comment by jordansexton** [comment] 2015-05-06 21:07
I've run into the same thing. It's related to https://github.com/facebook/react/issues/3399 but I haven't resolved it in my own app yet.

**Comment by airwin** [comment] 2015-05-07 03:30
I think it's because the syntax highlighter didn't work in the server side, as @acdlite said in another issue.

**Comment by johanneslumpe** [comment] 2015-05-30 19:44
@acdlite can you confirm this?

**Comment by johanneslumpe** [comment] 2015-06-01 18:33
I just confirmed this myself. Closing this, because I don't think we will try to highlight markup on the server, as Prism has to access the DOM to do so.

**Closed by johanneslumpe** 2015-06-01 18:33 UTC
