### ISSUE TITLE
Access stores within action 

### ISSUE THREAD

**Issue by vesparny** [acdlite/flummox#23] opened 2015-02-13 11:30 UTC
I need to check Store's state within an action for caching purpose.
In the action I need to check if the store already contains data, otherwise I'll call my ApiUtils.

Is there a way to have Store access within Actions?

**Comment by vesparny** [comment] 2015-02-13 12:58
I guess the problem here is the registering order of Stores/Actions within the Flux instance
  ```js
 class Flux extends Flummox {
  constructor() {
    super();
    this.createActions('request', RequestActions, this);
    this.createActions('venues', VenuesActions, this);
    this.createActions('favorites', FavoritesActions, this);

    this.createStore('venues', VenuesStore, this);
    this.createStore('request', RequestStore, this);
  }
```
This way imagine that I need the RequestActions within every other actions. the only way to get it is to register it before every other actions.
Don't you think that way we could have soon circular dependencies issues?

**Comment by acdlite** [comment] 2015-02-13 14:46
You generally want your actions to be "pure" — they shouldn't depend on other actions, or on stores. If you need to do caching logic that uses the state of your stores, it may be better to do that in either your controller-view or even in the Flux class itself:

```js
class Flux extends Flummox {
  constructor() {...}

  async getThing(id) {
    if (!this.getStore('things').hasThing(id)) {
      // 
      return await this.getActions('things').getThing(id);
    }
  }
}
```

Or you could do this in a separate module and either mix in into your Flux class, or accept a Flux instance as a parameter.

Part of the problem is that the unidirectional nature of Flux isn't really well-suited to caching. I think the ideal solution is to handle caching completely within ApiUtils — using browser caching, localStorage, etc.

**Comment by vesparny** [comment] 2015-02-13 14:58
I'm facing another problem now that I think might be in the boundaries of this thread.
Using fluxible I was used to have similar scenarios:

* I fire an action `requestStart` that tells that an http request is running (the related store draws itself, and the view shows a spinner)
* the promise coming form the http request is handled in a store, and onSucces I want to fire two actions (one `requestStart` on another actions creator, and one `fetchingSuccess` on the same action)

How can I achieve this?

**Comment by vesparny** [comment] 2015-02-13 15:03
In general imagine that I want to have an app-wide actionsCreator like a request tracker.
I'd have the ability to hook into it from other actions in order to be able to change the related store.
Does it make sense?

**Comment by acdlite** [comment] 2015-02-13 15:04
@vesparny Re: your first comment, what you're describing is conceptually similar to an optimistic UI update. You can achieve this using the just-added `Store#registerAsync()`, which lets you register handlers for actions that fire at both the beginning and end of an asynchronous operation (and on errors):

https://github.com/acdlite/flummox/blob/master/docs/api/Store.md#registerasync

**Comment by acdlite** [comment] 2015-02-13 15:12
@vesparny I don't think you need an app-wide request tracker. You can just do it within your stores. Basic example:

```js
class ThingStore extends Store() {
  constructor(flux) {
    
    let thingActions = flux.getActions('things');
    this.registerAsync(thingActions.getThings, this.onGetThingsBegin, this.onGetThingsEnd, this.onGetThingsFailure);
    
    this.state = {
      isLoading: false,
      things: []
    };
  }
  
  onGetThingsBegin() {
    this.setState({ isLoading: true });
  }
  
  onGetThingsEnd(newThings) {
    this.setState({
      isLoading: false,
      things: this.state.things.concat(newThings)
    });
  }
}
```

**Comment by vesparny** [comment] 2015-02-13 15:12
It's incredible.
You always have an answer :)

I'll try the new method and let you know

**Comment by acdlite** [comment] 2015-02-13 15:16
@vesparny Awesome! I'm still pretty new to Flux as well, so it's nice to hear from people who are using it in different ways.

**Comment by vesparny** [comment] 2015-02-13 15:46
Just tried, this is my store

```javascript
class MyStore extends Store {
  constructor(flux) {
    super();
    var searchActionIds = flux.getActionIds('search');
    this.registerAsync(searchActionIds.search, this.handleSearchBefore, this.handleSearchSuccess, this.handleSearchError );
    this.state = {
      data:  []
    };
  }
  handleSearchSuccess(result) {
    this.flux.getActions('requests').endRequest();
    this.setState({
      data: result
    });
  }
  handleSearchBefore() {
   // Need to fire this action because I use a prop on the component to show/hide a spinner
    this.flux.getActions('requests').startRequest();
  }
  handleSearchError(err) {
    console.log(err);
  }
}
```

I got an error coming from the FB dispatcher:
```
Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
```
Maybe this will clarify a bit more my issue.
I'm pretty sure I'm making some conception mistake here.
Probably because I was used to do something like this with fluxible stack:
https://github.com/vesparny/morpheus/blob/develop/shared/actions/ContentActions.js#L24

**Comment by vesparny** [comment] 2015-02-13 15:48
It doesn't make sense to dispatch an action from a store, but where can I deal with this kind of situation where I need to notify a global Store?

Probably I should listen for that action to the other store?

**Comment by vesparny** [comment] 2015-02-13 15:50
Uhm, just saw your previous comment. You are right, I feel like a noob :)

**Comment by acdlite** [comment] 2015-02-13 15:52
@vesparny Haha, no worries. Flux less than a year old... we're all noobs :)

**Comment by vesparny** [comment] 2015-02-13 16:23
All is working well.
My actions are now just like this
```js
searchVenue(q){
    return Venue.getVenues(q);
  }
```

returning promises handled in the store. Neat.

I was just wondering hot to deal with global stores.
Imagine the case I want to track requests, and block the UI on every http request.
How would you manage that within the flux philosophy? Considering that I'm not able to achieve this dispatching multiple actions like I did in fluxible for instance.

**Comment by acdlite** [comment] 2015-02-13 16:49
@vesparny Hmm... in your global store, you could create handlers and register them with every request action. Obviously this doesn't scale well.

Or you could do it the "old-fashioned" way by accessing the FB dispatcher at `flux.dispatcher` and manually constructing a payload with a field indicating that it is a request action. Then, in your global store, use `flux.dispatcher.register()` to register a callback with an if statement to check if the action is a request action.

In this particular case, it may even be best to go outside of Flux and just use events. Create an EventEmitter that fires at the beginning and end of every request, and have your views subscribe to them. You could even create the EventEmitter inside your Flux class so everything is still encapsulated. (If it's a client-side only thing, though, you could even get away with using a singleton.) Just an idea.

**Comment by acdlite** [comment] 2015-02-13 16:54
@vesparny Thinking about this more, though, it seems like you should be able to handle this with a helper method on the Flux class:

```js
class Flux extends Flummox {
    constructor() {...}

    async makeApiRequest() {
      flux.getActions('global').beginRequest();

      let response = await someServerOperation();

      flux.getActions('global').endRequest();

      return response;
    }
}
```

Again, just throwing out ideas here. Have you tried something like that?

**Comment by acdlite** [comment] 2015-03-06 05:35
Closing this because the original issue seems to be resolved. We can continue the conversation elsewhere if you like.

**Closed by acdlite** 2015-03-06 05:35 UTC
